### ISSUE TITLE
Unpacking URootfs.bin.gtx1

### ISSUE THREAD

**Issue by AnixPasBesoin** [jhermsmeier/hp-futuresmart-bundle#1]
Hi, thanks for publishing your tool @jhermsmeier 

I have been able to unpack the first level of a ".bdl" raw firmware image for "HP_Color_LaserJet_Pro_MFP_3301-3388", however I am not able to go beyond that (even when using binwalk and other file carcing tools). Here's what I have so far:

```
├── lbi
│   ├── Ulbi.bin.gtx1
│   └── digests.txt
└── rootfs
    ├── URootfs.bin.gtx1
    └── digests.txt
```

I would appreciate hints/directions on unpacking the gtx1 files. :))

**Comment by jhermsmeier** [comment]
Hi @AnixPasBesoin! I'm a bit amazed that this tool is finding some use :)

I've not come across ".gtx1" files yet, but I've downloaded the firmware and had a quick look.
My first guess would've been a squashfs, or compressed ext4 image (since I've seen that in firmware for other models), but that does not appear to be the case here.

A quick look at a hexdump of the file doesn't reveal anything obvious to me, other than some interestingly spaced null-bytes with everything in between being quite high entropy, which makes me think that "gtx1" refers to a compression scheme, or possibly another HP custom file format (they seem to like coming up with their own file formats).

The internet also doesn't seem to know about any file format or compression scheme called "gtx" or "gtx1"; the only thing I could find were some Atmel application notes / data sheets for a chip with a pin called "GTX1", and some linux config for said chips. Not sure if those have any connection to each other, but that's all I got.

Since I don't really have a use for this tool myself, I probably won't spend more time on figuring out what this specific format is, unless curiosity get's the better of me. (I only wrote this because I was curious what kind of software printers run internally.) But please do let me know if you find out what it is!

**Comment by jhermsmeier** [comment]
It just occured to me that that model might be running from raw flash memory, so these could be UBIFS images, which could be a reason why the usual file carving tools don't see anything, as that uses header-less LZO compression.
